name: UNISTOCK
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.1.0
  dots_indicator: ^2.0.0
  firebase_storage: ^12.1.1
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  image_picker: ^1.0.0
  flutter_local_notifications: ^16.3.3
  intl: ^0.19.0
  path: ^1.8.0
  cupertino_icons: ^1.0.6
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.0  # Added flutter_launcher_icons for generating app icons

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Uni-Icon.png"  # Specifies the app icon image path

flutter:
  uses-material-design: true

  assets:
    - assets/images/Uni-Icon.png
    - assets/images/sti announcement 1.png
    - assets/images/sti announcement 2.png
    - assets/images/sti announcement 3.png
    - assets/images/college uniform.png
    - assets/images/shs uniform.png
    - assets/images/washdayshirt.png
    - assets/images/bsit and bscpe.png
    - assets/images/bsa and bsba.png
    - assets/images/hrm and culinary.png
    - assets/images/tourism.png
    - assets/images/tourism1.png
    - assets/images/bacomm.png
    - assets/images/SHS DisplayU.png
    - assets/images/washdayshirt1.png
    - assets/images/washdayshirt2.png
    - assets/images/clothing1.png
    - assets/images/clothing2.png
    - assets/images/clothing3.png
    - assets/images/waterbottle.png
    - assets/images/wearablepins.png
    - assets/images/lacesC.png
    - assets/images/lacesSHS.png
    - assets/images/38thanniversary.png
    - assets/images/STI Facemask.png
    - assets/images/profilepict.png
    - assets/images/SHS_APRON.png
    - assets/images/SHS_PANTS.png
    - assets/images/SHS_NECKTIE.png
    - assets/images/SHS_BLOUSE_WITH_VEST.png
    - assets/images/SHS_SKIRT.png
    - assets/images/STI_WHITE_CHEF_LONG_SLEEVE_BLOUSE.png
    - assets/images/STI_LONG_CHECKERED_PANTS.png
    - assets/images/SHS_PE_PANTS.png
    - assets/images/SHS_PE_SHIRT.png
    - assets/images/STI_CHECKERED_BEANIE.png
    - assets/images/SHS_WASHDAY.png
    - assets/images/SHS_POLO_WITH_VEST.png
    - assets/images/IT_BLAZER.png
    - assets/images/IT_PANTS.png
    - assets/images/IT_POLO.png
