// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2aSmLHziXSvApGm8DSUGgLj0Wig8J4DI',
    appId: '1:735169171366:web:4f648fcd25a6a57dae0967',
    messagingSenderId: '735169171366',
    projectId: 'unistock-266e8',
    authDomain: 'unistock-266e8.firebaseapp.com',
    storageBucket: 'unistock-266e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-rxxMXf6Osq4Tr5qlnEkjHWACwapQvsc',
    appId: '1:735169171366:android:4f6ee5e544b69df0ae0967',
    messagingSenderId: '735169171366',
    projectId: 'unistock-266e8',
    storageBucket: 'unistock-266e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtRVT7Ll9OaYsGno6AbhvgcjANIeCD3Yc',
    appId: '1:735169171366:ios:9799fea874e67dddae0967',
    messagingSenderId: '735169171366',
    projectId: 'unistock-266e8',
    storageBucket: 'unistock-266e8.appspot.com',
    iosBundleId: 'com.example.unistock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtRVT7Ll9OaYsGno6AbhvgcjANIeCD3Yc',
    appId: '1:735169171366:ios:9799fea874e67dddae0967',
    messagingSenderId: '735169171366',
    projectId: 'unistock-266e8',
    storageBucket: 'unistock-266e8.appspot.com',
    iosBundleId: 'com.example.unistock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2aSmLHziXSvApGm8DSUGgLj0Wig8J4DI',
    appId: '1:735169171366:web:ba458640fea9fdcbae0967',
    messagingSenderId: '735169171366',
    projectId: 'unistock-266e8',
    authDomain: 'unistock-266e8.firebaseapp.com',
    storageBucket: 'unistock-266e8.appspot.com',
  );
}
